### ISSUE TITLE
Missing Spanish translation for primaryButton in userProfile.start.profileSection

### ISSUE THREAD

**Issue by ben-founded** [clerk/clerk-docs#1011]
When specifying the esES localization in the ClerkProvider component, the following key returns an empty string:

data-localization-key="userProfile.start.profileSection.primaryButton"

The Spanish translation of "Update profile" as specified in enUS for the key, within the context of a web application, is "Actualizar perfil"

**Comment by LekoArts** [comment]
Hi, thanks for the issue!

You can provide your own localization to add your desired value: https://clerk.com/docs/components/customization/localization#custom-localizations

If you want to make it available to everyone you can also send in a PR to https://github.com/clerk/javascript which is explained here: https://clerk.com/docs/components/customization/localization#adding-or-updating-a-localization
