### ISSUE TITLE
Missing bun as package manager

### ISSUE THREAD

**Issue by nirzon47** [clerk/clerk-docs#1058]
The documentation currently does not include any information on using Bun as a package manager.

This could be beneficial for developers who prefer Bun over other package managers.

**Comment by LekoArts** [comment]
Hey! As mentioned in https://github.com/clerk/clerk-docs/pull/1059#issuecomment-2122949029 we won't add this in the near future so for now I'm closing this. Once we are sure we support it we'll add it as an option. Thanks for the suggestion!
