### ISSUE TITLE
Incorrect property name for email address in Clerk "Handling webhooks with Ingest" documentation

### ISSUE THREAD

**Issue by rupaut98** [clerk/clerk-docs#1126]
The Clerk webhook documentation for Inngest integration contains an incorrect property name for accessing the user's email address. I had a similar issue a few days ago. The issue was in "src/inngest/welcome-emails.ts." There is a similar issue in "src/inngest/sync-user.ts." The property should be email_address instead of email.

The current code in the documentation:
```
const email = user.email_addresses.find(e =>
  e.id === user.primary_email_address_id
).email;
```

The corrected code should be:
```
const email = user.email_addresses.find(e =>
  e.id === user.primary_email_address_id
).email_address;
```

**Comment by alexisintech** [comment]
@rupaut98 this is a bug and it's on our map! sorry about that

USER-39
