### ISSUE TITLE
Module '"@clerk/nextjs"' has no exported member 'authMiddleware'.

### ISSUE THREAD

**Issue by mahmed74** [clerk/clerk-docs#1144]
The Clerk webhook documentation seems outdated under "Webhooks > Sync Clerk Data to your application with webhooks"
(https://clerk.com/docs/integrations/webhooks/sync-data)

the auth middleware shows an import in docs

`import { authMiddleware } from "@clerk/nextjs";`

`export default authMiddleware({
  ignoredRoutes: ["/api/webhooks(.*)"],
});`

`export const config = {
  matcher: ['/((?!.*\\..*|_next).*)', '/', '/(api|trpc)(.*)'],
};`

which throws an error that 
`Module '"@clerk/nextjs"' has no exported member 'authMiddleware'.`

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

`import { authMiddleware } from "@clerk/nextjs"` needs to be changed to `import { authMiddleware } from "@clerk/nextjs/server"`

If you're up for it, please open a PR improving our docs 😊 
You can find all relevant information on how to get started in our [contributing documentation](https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md). Thanks!

**Comment by sAndrin3** [comment]
If you are using NextJs 14, there is a change from authMiddleware to clerkMiddleware.

In the docs, clerkMiddleware appears to be 
```
import { clerkMiddleware } from "@clerk/nextjs/server";

export default clerkMiddleware();

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
};
```

Causing an issue with afterSignOutUrl = "/" which is depreciated when using <UserButton/>.

Here is an update on clerkMiddleware which resolves that issue

```
import { clerkMiddleware, createRouteMatcher  } from "@clerk/nextjs/server";

const isPublicRoute = createRouteMatcher(['/sign-in(.*)', '/sign-up(.*)']);

export default clerkMiddleware((auth, request) => {
  if(!isPublicRoute(request)) {
    auth().protect();
  }
});

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
};
```
And now you can use 

```
import {UserButton } from '@clerk/nextjs';


export default function Home() {
  return (
    <div>
        <UserButton/>
    </div>
  );
}
```
and get the expected results.
