### ISSUE TITLE
Deprecated verifySession Method Used in Documentation for Manual Authentication

### ISSUE THREAD

**Issue by rupaut98** [clerk/clerk-docs#1147]
The current documentation on [Clerk Node.js overview](https://clerk.com/docs/references/nodejs/overview) contains deprecated method verifySession which is no longer supported as per the [verify-session documentation](https://clerk.com/docs/references/backend/sessions/verify-session).

Specifically, the following sections need updating:

1. [Authenticate a particular session](https://clerk.com/docs/references/nodejs/overview#authenticate-a-particular-session)

```
import { sessions } from '@clerk/clerk-sdk-node';
import Cookies from 'cookies';

// Retrieve the particular session ID from a
// query string parameter
const sessionId = req.query._clerk_session_id;

// Note: Clerk stores the clientToken in a cookie
// named "__session" for Firebase compatibility
const cookies = new Cookies(req, res);
const clientToken = cookies.get('__session');

const session = await sessions.verifySession(sessionId, clientToken);
```
2. [Authenticate the last active session](https://clerk.com/docs/references/nodejs/overview#authenticate-the-last-active-session)
```
import { clients, sessions } from '@clerk/clerk-sdk-node';
import Cookies from 'cookies';

// Note: Clerk stores the clientToken in a cookie
// named "__session" for Firebase compatibility
const cookies = new Cookies(req, res);
const clientToken = cookies.get('__session');

const client = await clients.verifyClient(clientToken);
const sessionId = client.lastActiveSessionId;

const session = await sessions.verifySession(sessionId, clientToken);
```

These sections need to be updated to reflect the new method for verifying sessions. This will ensure that the documentation is accurate and developers are not misled by deprecated methods.

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

If you're up for it, please open a PR improving our docs 😊 
You can find all relevant information on how to get started in our [contributing documentation](https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md). Thanks!

**Comment by kevinzunigacuellar** [comment]
It looks like this issue might have been resolved in https://github.com/clerk/clerk-docs/pull/1205
