### ISSUE TITLE
Feedback for “<UserButton />”

### ISSUE THREAD

**Issue by MarekVavrovic** [clerk/clerk-docs#1148]
Hi, afterSignOutUrl property of "UserButton" is  malfunctioning. Instead of navigate to the url I've specified it goes to this one: "https://divine-sawfish-41.accounts.dev/sign-in?redirect_url=http%3A%2F%2Flocalhost%3A3000%2Fadd-job". 

code example:
import LinksDropdown from "./LinksDropdown";
import { UserButton } from "@clerk/nextjs";
import ThemeToggle from "./ThemeToggle";

function Navbar() {
  return (
    <nav className="bg-muted py-4 sm:px-16 lg:px-24 px-4 flex items-center justify-between">
      <div>
        <LinksDropdown />
      </div>
      <div className="flex items-center gap-x-4">
        <ThemeToggle />
        <UserButton afterSignOutUrl="/" />
      </div>
    </nav>
  );
}
export default Navbar;

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

Please reach out to our support or go onto our Discord if you have questions: https://clerk.com/contact
