### ISSUE TITLE
Invalid alert type ﻿[!INFO] in 'Verify the active user's permissions in an organization' documentation

### ISSUE THREAD

**Issue by bookercodes** [clerk/clerk-docs#1165]
In Verify the active user's permissions in an organization, under [How to add types for roles and permissions](https://clerk.com/docs/organizations/verify-user-permissions#how-to-add-types-for-roles-and-permissions), the alert references `[!INFO]`, but [`[!INFO]` not a support alert type](https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md#highlighting):

<img width="813" alt="image" src="https://github.com/clerk/clerk-docs/assets/11927968/eb7a3bce-cd15-4a20-b64e-c82268aebf41">

I was about to submit a pull request, but I can't decide what alert type would be inline with the convention you use across the documentation. 

I think it looks like a [!NOTE]. If what works for you, I'll make a PR .

**Comment by kevinzunigacuellar** [comment]
I agree that it should be a note as well.

The current explanation might be a bit tricky for some to follow. How about rephrasing it like this?

> By default, roles and permission types like `OrganizationCustomRoleKey` and `OrganizationCustomPermissionKey` are assigned `string`. However, if you define a `ClerkAuthorization` type in your project, this will be used instead.
