### ISSUE TITLE
supabase guide is outdated

### ISSUE THREAD

**Issue by kenhuang1964** [clerk/clerk-docs#1235]
![image](https://github.com/clerk/clerk-docs/assets/87556616/bfd4fb39-8aac-42f8-8075-167678b575cc)

I followed this guide: https://clerk.com/docs/integrations/databases/supabase

**Comment by MincePie** [comment]
have you figured out how to get started? this repo seems to have figured some things out: https://github.com/Ali-Onar/nextjs-supabase-todo-app/tree/main/app

im 2 days into trying to figure out a basic config to get this up and running - and very much stuck
