### ISSUE TITLE
UserButton Doesn't Display 

### ISSUE THREAD

**Issue by Pt-Lin** [clerk/clerk-docs#1236]
Although I have imported UserButton and ClerkProvider into my code, the page doesn't show UserButton:
![image](https://github.com/clerk/clerk-docs/assets/82385031/656008b0-ef7d-45e1-81f9-b1e1d88eb9c6)
![image](https://github.com/clerk/clerk-docs/assets/82385031/8b2003ce-f4b2-4315-acfa-8bb98708f337)
And I think lots of people have met the same problems, which you can find in this discussion: https://github.com/adrianhajdin/threads/issues/73

**Comment by LekoArts** [comment]
Hey, thanks for the issue!

Please reach out to our support or go onto our Discord if you have questions: https://clerk.com/contact
