### ISSUE TITLE
CONTRIBUTING.md updates

### ISSUE THREAD

**Issue by bookercodes** [clerk/clerk-docs#1447]
Jotting these down before I forget!

There are a few undocumented features mdx features

- `title` vs `fileName` in code blocks (the difference and best practices)
- New `<Callout />` component
- Context/rationale and guidance behind `prettier` formatting in code blocks (I think it can throw the build now?)

I learned about them here and there, but it would definitely be beneficial to for future contributors to mention in [CONTRIBUTING.md](https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md#contributing-to-clerks-documentation)

**Comment by bradlc** [comment]
> _Context/rationale and guidance behind `prettier` formatting in code blocks (I think it can throw the build now?)_

I added some info about formatting here: https://github.com/clerk/clerk-docs/pull/1437

> New `<Callout />` component

This is documented here: https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md#callouts

> _`title` vs `fileName` in code blocks (the difference and best practices)_

I'm going to think about this some more before documenting!
