### ISSUE TITLE
clerkMiddleware with Nextjs error :  InvalidCharacterError: Invalid character     at atob (node:buffer:1335:13)  digest: "1504358010"

### ISSUE THREAD

**Issue by mohamedmubaader** [clerk/clerk-docs#1506]
Hi,

I am trying to use clerkMiddleware with Nextjs but i am keep getting below  error :  

![image](https://github.com/user-attachments/assets/3c1c1045-1307-4044-9d34-5c0d0075eed6)

any advise how to solve it ?

**Comment by LekoArts** [comment]
Hi, please use https://clerk.com/contact as this issue tracker is not for support requests. Thanks!
