### ISSUE TITLE
Incorrect use of auth().redirectToSignin() in docs page

### ISSUE THREAD

**Issue by pippinmole** [clerk/clerk-docs#1649]
Referenced section: https://clerk.com/docs/references/nextjs/clerk-middleware#protect-routes-based-on-user-authentication-status

It states the following middleware.ts code is valid, under the ``auth().userId()`` tab:

```ts
import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server'

const isProtectedRoute = createRouteMatcher(['/dashboard(.*)', '/forum(.*)'])

export default clerkMiddleware(async (auth, req) => {
  const { userId } = await auth()

  if (!userId && isProtectedRoute(req)) {
    // Add custom logic to run before redirecting

    return auth().redirectToSignIn()
  }
})

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
}
```

However, ``auth``is an async function which does not have this ``redirectToSignin()`` function (without awaiting auth a second time). I believe the code should be as such:
```ts
import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server'

const isProtectedRoute = createRouteMatcher(['/dashboard(.*)', '/forum(.*)'])

export default clerkMiddleware(async (auth, req) => {
  const { userId, redirectToSignIn } = await auth()

  if (!userId && isProtectedRoute(req)) {
    // Add custom logic to run before redirecting

    return redirectToSignIn()
  }
})

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
}
```

**Comment by derweili** [comment]
Has the behavior of the `auth()` function changed recently. Because this [blog post](https://clerk.com/blog/add-onboarding-flow-for-your-application-with-clerk#add-user-update-method-to-your-backend) about onbording flow has a similar mistake.
The `auth()` function in the middleware requires an `await`and the middleware function itself must therefore be a async function.

**Comment by alexisintech** [comment]
Yes! It was changed recently in our [`@clerk/nextjs` v6 release](https://clerk.com/changelog/2024-10-22-clerk-nextjs-v6) (which was released in response to the new [Next.js 15](https://nextjs.org/blog/next-15))

Thank you for pointing this out, and its being updated in this PR: https://github.com/clerk/clerk-docs/pull/1658

as for the blog posts, I will bring it to our marketing teams attention!
