### ISSUE TITLE
rendering-modes docs page redirect to a 404

### ISSUE THREAD

**Issue by RicardoGEsteves** [clerk/clerk-docs#1663]
Hi,
Just used codemod to migrate to clerk/next v6 and after the migration process had an issue to resolve and it was provided this link `https://clerk.com/docs/nextjs/rendering-modes` which redirect me for a 404 page.

<img width="1288" alt="Screenshot 2024-10-27 at 13 30 44" src="https://github.com/user-attachments/assets/f8da48d8-906d-4194-9852-ba1958e3fd32">

**Comment by alexcarpenter** [comment]
Fixed in https://github.com/clerk/javascript/pull/4459
