### ISSUE TITLE
Duplication on "Create users" sidebar link

### ISSUE THREAD

**Issue by p3yman** [clerk/clerk-docs#1757]
Hi,

There are 2 "Create users" links on the sidebar targeting the same page.

https://clerk.com/docs/users/creating-users

<img width="339" alt="Screenshot 2024-12-02 at 11 33 49" src="https://github.com/user-attachments/assets/16e0dcbd-4712-4ce9-a305-017d2d9c6abc">

**Comment by victoriaxyz** [comment]
Hi @p3yman! Thanks for letting us know. This issue has been fixed. Appreciate the callout!
