### ISSUE TITLE
Type error: 'ClerkProvider' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by leoceolin** [clerk/clerk-docs#1780]
I'm using
"@clerk/nextjs": "^6.7.1",
"next": "14.2.13",

here is my layout.tsx file

```
import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { TooltipProvider } from '@/components/ui/tooltip'
import { AppSidebar } from '@/components/AppSideBar'
import { SidebarProvider } from '@/components/ui/sidebar'

export const metadata: Metadata = {
  title: 'App',
  description: 'App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
 <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
          <SidebarProvider>
            <AppSidebar />
            <TooltipProvider>{children}</TooltipProvider>
          </SidebarProvider>
      </body>
    </html>
  </ClerkProvider>
  )
}
```

and i'm having this error

> Type error: 'ClerkProvider' cannot be used as a JSX component.
>   Its type '(props: Without<NextClerkProviderProps, "__unstable_invokeMiddlewareOnAuthStateChange">) => Promise<Element>' is not a valid JSX element type.
>     Type '(props: Without<NextClerkProviderProps, "__unstable_invokeMiddlewareOnAuthStateChange">) => Promise<Element>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
>       Type 'Promise<Element>' is not assignable to type 'ReactNode'.

any one can help me? it's crashing my app and i really don't know why exactly this is happening it was working normally and then started crashing

**Comment by nasirumuhammad** [comment]
am facing same issue here, i have build app previously with it but a now facing the issue

**Comment by RayFernando1337** [comment]
I'm seeing the same issue today. I went to re-deploy and got hit with the same issue. I think this should be marked as a high priority due to it breaking existing pinned versions of Clerk with Next.js 14.

**Comment by LekoArts** [comment]
Please use the correct issue tracker at https://github.com/clerk/javascript/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen or reach out to our support: https://clerk.com/contact

**Comment by antonioc-cl** [comment]
From Clerk Discord:
```
Hey folks, we've have quite a few reports of users running into this type of error when spinning up new NextJs apps or upgrading older apps. Here's how to resolve the error:

This error is caused by @types/react version 18.3.14. If you run into this issue we recommend the following versions.

If using Next 15, you'll have to have the following versions to resolve the error:
  "next": "15.0.4",
  "react": "^19.0.0",
  "react-dom": "^19.0.0",
  "@types/react": "^19.0.1",


If using Next 14, you can utilize the following versions:
  "next": "14.2.20",
  "react": "^18.3.1",
  "react-dom": "^18.3.1",
  "@types/react": "^18.3.12",

You'll have to stay on this version until this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71388) is merged.
```
