### ISSUE TITLE
Node/Express Backend Request Page from Sanity CMS to MDX 

### ISSUE THREAD

**Issue by HondaChan14** [clerk/clerk-docs#263]
# Summary
I would like to contribute in migrating following clerk doc page from Sanity CMS to MDX:

[Handling requests with Node.js and Express](https://clerk.com/docs/backend-requests/handling/nodejs)

## Acceptance criteria
- [ ] Ensure all the content and links are the same and functional
- [ ] Use proper MDX components

**Comment by alexisintech** [comment]
Approved! 😸✅

**Comment by royanger** [comment]
Looks like this was all completed in [PR 377](https://github.com/clerk/clerk-docs/pull/377). I believe that we can close this @HondaChan14? Close with a big thank you for the work!

**Comment by alexisintech** [comment]
Yes! We can close this one out :)
