### ISSUE TITLE
UserButton Name Direction

### ISSUE THREAD

**Issue by sakgoyal** [clerk/clerk-docs#595]
Is there a way to change the direction of the text when `showName` is enabled?
currently it defaults to show the name on the left of the icon. can there be a way to flip them so I can have this component on the left side of the screen?

**Comment by megancooper** [comment]
I was able to do this by applying a custom `flex-direction` style to the `userButtonBox` element 👀 

```tsx
<UserButton
  appearance={{
    elements: {
      userButtonBox: {
        flexDirection: "row-reverse",
      },
    },
  }}
  showName
/>
```

**Comment by sakgoyal** [comment]
oh thats perfect. but I also want to know if its possible to change the click target so I can click on the name of the user to also open the menu instead of just being able to click on the profile image. Is that something I can change?

**Comment by rheav** [comment]
> ```tsx
>  appearance={{
>     elements: {
>       userButtonBox: {
>         flexDirection: "row-reverse",
>       },
>     },
>   }}
> ```

This was perfect, thanks!

**Comment by rheav** [comment]
@megancooper thanks for this!

**Comment by LekoArts** [comment]
Please visit our Discord server or create a ticket if you have questions about using Clerk: https://clerk.com/contact
