### ISSUE TITLE
Props not fully documented?

### ISSUE THREAD

**Issue by Simbaclaws** [clerk/clerk-docs#639]
Dear Clerk,

I'm currently trying to alter the appearance of the UserButton, there is a prop called appearance available, but I can not see in the docs what this appearance has for options to supply.

Do I have to check the source code to figure out what I can pass to it?

I'm just trying to make the userbutton avatar icon a bit bigger.

Please help.

Yours truly,
Hylke

**Comment by LekoArts** [comment]
Hi, thanks for asking!

The `appearance` prop is documented here: https://clerk.com/docs/components/customization/overview

**Comment by Simbaclaws** [comment]
Ah, I couldn't find this page for some reason, thank you so much, I'll have a look later
