### ISSUE TITLE
Add more clarification to the Organizations > Verified Domains page

### ISSUE THREAD

**Issue by ntswarup** [clerk/clerk-docs#687]
https://github.com/clerk/clerk-docs/edit/main/docs/organizations/verified-domains.mdx

After a user has turned on the Verified Domains setting in the Clerk dashboard, it's unclear whether they're able to add a verified domain for an organization within the dashboard, or whether they need to use the API. 

The help center content reads like it's available as an option within the dashboard, but it's not obvious how to actually do this.

To improve the documentation:
1. It should be clear whether a Clerk user can add a verified domain for an organization within the Clerk dashboard, or whether it must be done through an API call.
2. It should provide step-by-step instructions on how to actually create a domain for an organization, and how to verify it (e.g. how to trigger sending the email verification code mentioned in the documentation)

**Comment by alexisintech** [comment]
Updated this page in May - should have a better explanation now ! https://github.com/clerk/clerk-docs/commit/15ebc8a416533fe637817a574a69acc7cdddb9be
