### ISSUE TITLE
Fix links to examples in Quickstarts section

### ISSUE THREAD

**Issue by fmerian** [clerk/clerk-docs#741]
Hello, Clerkians 👋 

In the Quickstarts section, [^1] links to examples (guides and tutorials) lead to old page layouts.

See screen recording here (Chrome 122.0.6261.69): https://share.cleanshot.com/kzrXTyVd

Keep up your great work 😄 

[^1]: https://clerk.com/docs/quickstarts/overview

**Comment by LekoArts** [comment]
This has been fixed in the meantime 👍
