### ISSUE TITLE
There is no redirectUrl option in SignOutButton

### ISSUE THREAD

**Issue by Hero-codes** [clerk/clerk-docs#817]
https://clerk.com/docs/components/unstyled/sign-out-button#sign-out-options
According to this, there must be a redirectUrl
![image](https://github.com/clerk/clerk-docs/assets/98174971/5fb139b4-d6ef-4ee9-9234-60749f626124)
But in reality, there is no option. It gives an error
![image](https://github.com/clerk/clerk-docs/assets/98174971/dabaf229-de30-4722-ab75-d04b6698a50a)
Kindly fix the issue

**Comment by rhijjawi** [comment]
@Hero-codes 
https://github.com/clerk/clerk-docs/pull/818

**Comment by alexisintech** [comment]
It lives in our Core-2 update!
We have a new release of Clerk called Core-2, and it is currently in beta. You can visit the beta docs for this specific component [here](https://beta.clerk.com/docs/components/unstyled/sign-out-button), and the `redirectUrl` prop is available.
