### ISSUE TITLE
User Metadata page does not explain the lack of support for organization memberships

### ISSUE THREAD

**Issue by ryan-saffer** [clerk/clerk-docs#852]
I have been building a custom roles/permissions solution using user metadata to store the users role against their org. (Something I was recommended to do by the Clerk sales team).

However it appears that a users public metadata is only available if using the `users` API to `getUserList()`. If I use the `users` API to `getOrganizationMembershipList()` or the `organizations` API to `getOrganizationMembershipList()`, the users public metadata is always an empty object, `{}`.

Ideally this issue is fixed in the core API, but until then, the docs should correctly reflect this limitation.

**Comment by alexisintech** [comment]
`getOrganizationMembershipList()` returns a list of `OrganizationMembership` objects. The `publicMetadata` you are seeing is actually `OrganizationMembership.publicMetadata` , it is not `User.publicMetadata`... as in, it's the public metadata associated with that organization membership, not the user.

also, we offer custom [roles](https://clerk.com/docs/organizations/roles-permissions#custom-role) and [permissions](https://clerk.com/docs/organizations/roles-permissions#custom-permissions), so I hope you are aware of that 🫶
