### ISSUE TITLE
Improving Documentation: Addressing the Issue with Implementing RBAC

### ISSUE THREAD

**Issue by Ehren12** [clerk/clerk-docs#910]
While exploring the documentation for [Implementing basic Role Based Access Control (RBAC) with metadata](https://clerk.com/docs/guides/basic-rbac), I encountered an issue that needs attention:

> It is worth knowing that I am using **Clerk Core 2.0.**.

![Screenshot 2024-04-16 130802](https://github.com/clerk/clerk-docs/assets/61390454/c1ff1d6a-6ef1-4f18-a02d-8326f7993444)

The issue arises from the fact that `await clerkClient.users.getUserList({ query })` does not directly return an array as expected.

### Proposed Solution
To address this issue, we can simply access the data field returned by `clerkClient.users.getUserList({ query })`. By doing so, we ensure that we retrieve the array of users correctly.

Here's how to implement the correction:
`const users = query ? (await clerkClient.users.getUserList({ query })).data : [];`

By making this adjustment, we ensure that the code accurately captures the array of users, resolving the issue encountered.

I would appreciate any feedback on this proposed solution and would be glad to make further adjustments as needed.

**Comment by alexisintech** [comment]
would you like to make a PR to incite this change?
simply clone the docs repo, open the page, make the change, and then submit the PR :~) be sure to include "Resolves Issue 910" in the title of the PR

**Comment by Ehren12** [comment]
Yes i will love to sorry im replying this late.
