### ISSUE TITLE
docs URLs from github changelog redirect to a 404

### ISSUE THREAD

**Issue by RicardoGEsteves** [clerk/clerk-docs#917]
https://github.com/clerk/javascript/releases

[@clerk/themes@2.0.0](https://github.com/clerk/javascript/releases/tag/%40clerk%2Fthemes%402.0.0)

> wrong address: For more info, refer to the [upgrade guide from v4 to v5 in Clerk docs](https://clerk.com/docs/upgrade-guides/upgrading-from-v4-to-v5).

[@clerk/nextjs@5.0.0](https://github.com/clerk/javascript/releases/tag/%40clerk%2Fnextjs%405.0.0)

> wrong address: Deprecate authMiddleware in favor of clerkMiddleware. For more information, see https://clerk.com/docs/upgrade-guides/v5-introduction

**Comment by LekoArts** [comment]
Hi, thanks for the pointer. The GitHub releases will be updated shortly to correctly point people towards our docs.

You can find them here: https://clerk.com/docs/upgrade-guides/core-2/overview

**Comment by RicardoGEsteves** [comment]
> Hi, thanks for the pointer. The GitHub releases will be updated shortly to correctly point people towards our docs.
> 
> You can find them here: https://clerk.com/docs/upgrade-guides/core-2/overview

Thanks LekoArts.
