### ISSUE TITLE
Update clerkClient import path

### ISSUE THREAD

**Issue by willalread** [clerk/clerk-docs#928]
In the Upgrading to Core 2 Next.js SDK guide, `clerkClient` is not listed in the "Changes to top-level exports" section under the list of exports that have moved from `@clerk/nextjs` to `@clerk/nextjs/server`.
https://clerk.com/docs/upgrade-guides/core-2/nextjs#changes-to-top-level-exports

It is currently listed incorrectly in the "Deleting users" section of the Users docs under the Next.js tab as still,
`import { clerkClient } from "@clerk/nextjs";`
https://clerk.com/docs/users/deleting-users

However, it is listed correctly in the "Overview" section of the Backend SDK docs under the Next.js tab as,
`import { clerkClient } from "@clerk/nextjs/server";`
https://clerk.com/docs/references/backend/overview

**Comment by alexisintech** [comment]
Fixed!
