### ISSUE TITLE
Improving documentation: Including more information about OIDC

### ISSUE THREAD

**Issue by mtander** [clerk/clerk-docs#937]
I know that Clerk supports SAML connections, but I don't understand if Clerk supports OIDC (this is a feature we are looking for in the system we use for authentication).  The only thing I could find about OIDC was in the Clerk Discord.  Please provide more information if at all possible in your documentation!  Thank you :-)

<img width="399" alt="image" src="https://github.com/clerk/clerk-docs/assets/13581894/f0c63247-ba20-4d38-9754-b792ed6636f4">

**Comment by alexisintech** [comment]
We don't currently support OIDC but you can upvote the feature request on our roadmap, and leave your email to be notified when the feature is released: https://feedback.clerk.com/roadmap?id=0672b226-0362-48fb-82bc-0f4ce83ba5b9
